title: High Yield Investment Program Milker
desc: Earn passive income with high yield investment programs
description: 'Earn passive income with high yield investment programs'
url: https://hyipmilker.com
baseurl: ''
permalink: '/:title.html'
ngrok: https://35fbaff9.ngrok.io/backend
exclude: [.git, .gitignore]
active_members: 578
transactions: 1558
profits: 6540
days_online: 22
programs: 43
ref_income: 566