title: High Yield Investment Program Milker
desc: Earn passive income with high yield investment programs
description: 'Earn passive income with high yield investment programs'
url: https://hyipmilker.com
baseurl: ''
permalink: '/:title.html'
ngrok: https://000ae0cc.ngrok.io/backend
exclude: [.git, .gitignore]
active_members: 226
transactions: 502
profits: 2056
days_online: 15
programs: 44
ref_income: 199