title: High Yield Investment Program Milker
desc: Earn passive income with high yield investment programs
description: 'Earn passive income with high yield investment programs'
url: https://hyipmilker.com
baseurl: ''
permalink: '/:title.html'
ngrok: https://d00aefb1.ngrok.io/x/hyipmilker/php-hyipmilker
exclude: [.git, .gitignore]
active_members: 4
transactions: 5.25
profits: 4
days_online: 10
programs: 46
ref_income: 0