title: High Yield Investment Program Milker
desc: Earn passive income with high yield investment programs
description: 'Earn passive income with high yield investment programs'
url: https://hyipmilker.com
baseurl: ''
permalink: '/:title.html'
ngrok: https://35fbaff9.ngrok.io/backend
exclude: [.git, .gitignore]
active_members: 440
transactions: 1120
profits: 4808
days_online: 19
programs: 43
ref_income: 395