title: High Yield Investment Program Milker
desc: Earn passive income with high yield investment programs
description: 'Earn passive income with high yield investment programs'
url: https://hyipmilker.com
baseurl: ''
permalink: '/:title.html'
ngrok: https://hyipmilker.com/backend
exclude: [.git, .gitignore]
active_members: 602
transactions: 1630
profits: 6699
days_online: 24
programs: 44
ref_income: 591