title: High Yield Investment Program Milker
desc: Earn passive income with high yield investment programs
description: 'Earn passive income with high yield investment programs'
url: https://hyipmilker.com
baseurl: ''
permalink: '/:title.html'
ngrok: https://79f0b017.ngrok.io/backend
exclude: [.git, .gitignore]
active_members: 139
transactions: 279
profits: 1221
days_online: 12
programs: 46
ref_income: 102