title: High Yield Investment Program Milker
desc: Earn passive income with high yield investment programs
description: 'Earn passive income with high yield investment programs'
url: https://hyipmilker.com
baseurl: ''
permalink: '/:title.html'
ngrok: https://000ae0cc.ngrok.io/backend
exclude: [.git, .gitignore]
active_members: 198
transactions: 455
profits: 1880
days_online: 14
programs: 44
ref_income: 167