title: High Yield Investment Program Milker
desc: Earn passive income with high yield investment programs
description: 'Earn passive income with high yield investment programs'
url: https://hyipmilker.com
baseurl: ''
permalink: '/:title.html'
ngrok: https://35fbaff9.ngrok.io/backend
exclude: [.git, .gitignore]
active_members: 313
transactions: 701
profits: 3150
days_online: 18
programs: 42
ref_income: 305