title: High Yield Investment Program Milker
  desc: Earn passive income with high yield investment programs
  description: 'Earn passive income with high yield investment programs'
  url: https://hyipmilker.com
  baseurl: ''
  permalink: '/:title.html'
  ngrok: https://d00aefb1.ngrok.io/x/hyipmilker/php-hyipmilker
  exclude: [wSERVEJEKYLL.bat, .gitignore, DRAFTS]
  active_members: 1
  transactions: 10
  profits: 100
  days_online: 10
  programs: 33
  ref_income: 1000