title: High Yield Investment Program Milker
desc: Earn passive income with high yield investment programs
description: 'Earn passive income with high yield investment programs'
url: https://hyipmilker.com
baseurl: ''
permalink: '/:title.html'
ngrok: https://79f0b017.ngrok.io/backend
exclude: [.git, .gitignore]
active_members: 4
transactions: 0
profits: 0
days_online: 11
programs: 47
ref_income: 0