title: High Yield Investment Program Milker
desc: Earn passive income with high yield investment programs
description: 'Earn passive income with high yield investment programs'
url: https://hyipmilker.com
baseurl: ''
permalink: '/:title.html'
ngrok: https://hyipmilker.com/backend
exclude: [.git, .gitignore]
active_members: 622
transactions: 1720
profits: 7200
days_online: 25
programs: 44
ref_income: 605