title: High Yield Investment Program Milker
desc: Earn passive income with high yield investment programs
description: 'Earn passive income with high yield investment programs'
url: https://hyipmilker.com
baseurl: ''
permalink: '/:title.html'
ngrok: https://hyipmilker.com/backend
exclude: [.git, .gitignore]
active_members: 599
transactions: 1620
profits: 6679
days_online: 23
programs: 44
ref_income: 590