title: High Yield Investment Program Milker
desc: Earn passive income with high yield investment programs
description: 'Earn passive income with high yield investment programs'
url: https://hyipmilker.com
baseurl: ''
permalink: '/:title.html'
ngrok: https://hyipmilker.com/backend
exclude: [.git, .gitignore]
active_members: 675
transactions: 1820
profits: 7520
days_online: 27
programs: 44
ref_income: 685