title: High Yield Investment Program Milker
desc: Earn passive income with high yield investment programs
description: 'Earn passive income with high yield investment programs'
url: https://hyipmilker.com
baseurl: ''
permalink: '/:title.html'
ngrok: https://d00aefb1.ngrok.io/backend
exclude: [.git, .gitignore]
active_members: 40
transactions: 48
profits: 98
days_online: 11
programs: 46
ref_income: 8